// Copyright 2024 The Podseidon Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	v1alpha1 "github.com/kubewharf/podseidon/apis/v1alpha1"
	apisv1alpha1 "github.com/kubewharf/podseidon/client/clientset/versioned/typed/apis/v1alpha1"
)

// fakePodProtectors implements PodProtectorInterface
type fakePodProtectors struct {
	*gentype.FakeClientWithList[*v1alpha1.PodProtector, *v1alpha1.PodProtectorList]
	Fake *FakePodseidonV1alpha1
}

func newFakePodProtectors(fake *FakePodseidonV1alpha1, namespace string) apisv1alpha1.PodProtectorInterface {
	return &fakePodProtectors{
		gentype.NewFakeClientWithList[*v1alpha1.PodProtector, *v1alpha1.PodProtectorList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("podprotectors"),
			v1alpha1.SchemeGroupVersion.WithKind("PodProtector"),
			func() *v1alpha1.PodProtector { return &v1alpha1.PodProtector{} },
			func() *v1alpha1.PodProtectorList { return &v1alpha1.PodProtectorList{} },
			func(dst, src *v1alpha1.PodProtectorList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.PodProtectorList) []*v1alpha1.PodProtector {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.PodProtectorList, items []*v1alpha1.PodProtector) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
