// Copyright 2024 The Podseidon Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	apisv1alpha1 "github.com/kubewharf/podseidon/apis/v1alpha1"
	versioned "github.com/kubewharf/podseidon/client/clientset/versioned"
	internalinterfaces "github.com/kubewharf/podseidon/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubewharf/podseidon/client/listers/apis/v1alpha1"
)

// PodProtectorInformer provides access to a shared informer and lister for
// PodProtectors.
type PodProtectorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodProtectorLister
}

type podProtectorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodProtectorInformer constructs a new informer for PodProtector type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodProtectorInformer(
	client versioned.Interface,
	namespace string,
	resyncPeriod time.Duration,
	indexers cache.Indexers,
) cache.SharedIndexInformer {
	return NewFilteredPodProtectorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodProtectorInformer constructs a new informer for PodProtector type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodProtectorInformer(
	client versioned.Interface,
	namespace string,
	resyncPeriod time.Duration,
	indexers cache.Indexers,
	tweakListOptions internalinterfaces.TweakListOptionsFunc,
) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodseidonV1alpha1().
					PodProtectors(namespace).
					List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PodseidonV1alpha1().
					PodProtectors(namespace).
					Watch(context.TODO(), options)
			},
		},
		&apisv1alpha1.PodProtector{},
		resyncPeriod,
		indexers,
	)
}

func (f *podProtectorInformer) defaultInformer(
	client versioned.Interface,
	resyncPeriod time.Duration,
) cache.SharedIndexInformer {
	return NewFilteredPodProtectorInformer(
		client,
		f.namespace,
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
		f.tweakListOptions,
	)
}

func (f *podProtectorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisv1alpha1.PodProtector{}, f.defaultInformer)
}

func (f *podProtectorInformer) Lister() v1alpha1.PodProtectorLister {
	return v1alpha1.NewPodProtectorLister(f.Informer().GetIndexer())
}
